name: Send Email on Failure

on:
  workflow_call:
    inputs:
      job_results:
        description: 'String of job results'
        required: true
        type: string
    secrets:
      EMAIL_USERNAME:
        required: true
      EMAIL_PASSWORD:
        required: true

jobs:
  send_email_on_failure:
    name: send_emails_when_fails
    runs-on: ubuntu-latest
    steps:
      - name: Get current date and set to env
        run: |
          echo "DATE=$(date +%m/%d)" >> $GITHUB_ENV

      - name: Send mail to mailing list
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # Subject: Uses the Repository name
          subject: ${{ env.DATE }} CI Failure in ${{ github.repository }} ${{ github.workflow }} workflow
          # Body: Lists the result of every job
          body: |
            The workflow ${{ github.workflow }} has failed.
            Job Status Report:
            ------------------
            ${{ inputs.job_results }}

            Check the details at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: solvcon@googlegroups.com
          from: solvcon_notification
